# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: devsecops-windows-java-agentpool

steps:
- script: |
    echo ------------------------Java Building------------------------
    java -version
    mvn clean install
  displayName: 'Java Building'

- script: |
    echo ------------------------Sonar Scanning------------------------
  displayName: 'Sonar Scanning'

- script: |
    echo ------------------------Security Scanning------------------------
  displayName: 'Security Scanning'

- script: |
    echo ------------------------Artifact Publish------------------------
  displayName: 'Artifact Publish'
